language: julia

os:
  - windows

julia:
  - 1.3.1

notifications:
  email: false

jobs:
  include:
    - stage: "Documentation"
      julia: 1.3.1
      os: windows
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
