language: julia
codecov: true
coveralls: true

os:
  - linux

julia:
  - 1.3.1

notifications:
  email: false

codecov: true
coveralls: true

jobs:
  include:
    - stage: "Documentation"
      julia: 1.3.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
